# Generated by Django 5.0.2 on 2024-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTDT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdt',
            name='sku_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productdt',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
