# Generated by Django 5.0.2 on 2024-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTDT', '0002_productdt_sku_code_productdt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdt',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productdt',
            name='sku_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productdt',
            name='sub_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productdt',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
