# Generated by Django 5.0.2 on 2024-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
