# Generated by Django 5.0.2 on 2024-04-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomUser', '0002_user_otp_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
