# Generated by Django 5.0.2 on 2024-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTPRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='Product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='delivery_charges',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='discount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='img1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='qty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='sku_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='total_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='total_qty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='user_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
