# Generated by Django 5.0.2 on 2024-05-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARTPRODUCT', '0003_addcart_reselling_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='reselling_margin',
            new_name='reselling_amount',
        ),
    ]
