# Generated by Django 5.0.2 on 2024-05-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARTPRODUCT', '0004_rename_reselling_margin_addcart_reselling_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='reselling_amount',
            new_name='reselling_margin',
        ),
    ]
