# Generated by Django 5.0.2 on 2024-05-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARTPRODUCT', '0005_rename_reselling_amount_addcart_reselling_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='reselling_margin',
            new_name='reselling_amount',
        ),
    ]
