# Generated by Django 5.0.2 on 2024-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
