# Generated by Django 5.0.2 on 2024-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_order_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reselling_margin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
