# Generated by Django 5.0.2 on 2024-05-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_reselling_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reselling_margin',
            new_name='reselling_amount',
        ),
    ]
