# Generated by Django 5.0.2 on 2024-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_reselling_margin_order_reselling_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resell_margin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
