# Generated by Django 5.0.2 on 2024-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
